multirepos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('relatorios/', include('relatorios.urls')),
    path('', RedirectView.as_view(url="relatorios/", permanent=False), name="siteindex"),
]

urlpatterns += staticfiles_urlpatterns()

relatorios/urls.py
from django.urls import path
from . import views

app_name = "relatorios"

urlpatterns = [
    path('', views.index, name="index"),
    path('produtos/', views.produtos, name="produtos"),
    path('caixas/', views.caixas, name="caixas"),
    path('ativos/', views.ativos, name="ativos"),
    path('estoques/', views.estoques, name="estoques"),
    path('containers/', views.containers, name="containers"),
    path('pedidos/', views.pedidos, name="pedidos"),
    path('itenspedidos/', views.itenspedidos, name="itenspedidos"),
    path('encomendas/', views.encomendas, name="encomendas"),
    path('verificar/', views.verificar, name="verificar"),
    path('xlsreport/', views.xlsReport, name="xlsreport"),

    path('uploadcv/', views.uploadcv, name="uploadcv"),
]

relatorios/models.py
from django.db import models

# Create your models here.

relatorios/forms.py
from django import forms


class UploadExcelForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'autofocus': 'autofocus'}))

class UploadTwoExcelsForm(forms.Form):
    file1 = forms.FileField()
    file2 = forms.FileField()


class PreliminaryReportForm(forms.Form):
    codigos = forms.CharField(widget=forms.Textarea, required=False)

relatorios/views.py
from datetime import date, timedelta, datetime
from calendar import monthrange
from collections import defaultdict

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db import transaction
from django.db.models import Sum

from fichas.models import Produto, Atualizado
from movimento.models import Chegando, Compra, Pedido, ItemPedido
from .forms import UploadExcelForm, UploadTwoExcelsForm, PreliminaryReportForm
from .excelio import produtos as xlprodutos
from .excelio import estoques as xlestoques
from .excelio import caixas as xlcaixas
from .excelio import ativos as xlativos
from .excelio import containers as xlcontainers
from .excelio import pedidos as xlpedidos
from .excelio import itenspedidos as xlitenspedidos
from .excelio import encomendas as xlencomendas
from .excelio import cv as xlcv
from .excelio.report import getBlocks, getXlsBlocks, generateXlsReport


def dataAtualizado(tipo):
    try:
        data = Atualizado.objects.get(tipo=tipo).data.strftime("%d/%m")
    except Atualizado.DoesNotExist:
        data = "--"
    return data


def fileUploadView(request, callback, formTemplate, templateVars):
    # https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/
    if request.method == "POST":
        form = UploadExcelForm(request.POST, request.FILES)
        if form.is_valid():
            response = callback(request.FILES['file'])
            return render(request, 'relatorios/result.html', {'response': response, 'templateVars': templateVars})
    else:
        form = UploadExcelForm()
        templateVars.update({'form': form})
        return render(request, formTemplate, templateVars)


def fileUploadTwoView(request, callback, formTemplate, templateVars):
    if request.method == "POST":
        form = UploadTwoExcelsForm(request.POST, request.FILES)
        if form.is_valid():
            response = callback(request.FILES['file1'], request.FILES['file2'])
            return render(request, 'relatorios/result.html', {'response': response, 'templateVars': templateVars})
    else:
        form = UploadTwoExcelsForm()
        templateVars.update({'form': form})
        return render(request, formTemplate, templateVars)
    
    
def index(request):
    # tipos = ["produtos", "caixas", "ativos", "estoques", "containers", "pedidos", "itenspedidos", "encomendas"]
    # atualizados = { t: dataAtualizado(t) for t in tipos }
    return render(request, 'relatorios/index.html')


def formDescription(request, tipo, callback):
    return fileUploadView(request, callback, 'relatorios/' + tipo + '.html', {'tipo': tipo, 'data': dataAtualizado(tipo)})


def produtos(request):
    return formDescription(request, "produtos", xlprodutos.create)
 

def caixas(request):
    return formDescription(request, "caixas", xlcaixas.create)


def ativos(request):
    return formDescription(request, "ativos", xlativos.create)


def estoques(request):
    return fileUploadTwoView(request, xlestoques.create, 'relatorios/estoques.html', {'tipo': 'estoques', 'data': dataAtualizado('estoques')})


def containers(request):
    return formDescription(request, "containers", xlcontainers.create)


def pedidos(request):
    return formDescription(request, "pedidos", xlpedidos.create)


def itenspedidos(request):
    return formDescription(request, "itenspedidos", xlitenspedidos.create)


def encomendas(request):
    return formDescription(request, "encomendas", xlencomendas.create)


def verificar(request):
    if request.method == "POST":
        form = PreliminaryReportForm(request.POST)
        if form.is_valid():
            return preliminaryReport(request, form.cleaned_data['codigos'])
    else:
        # get items that sold more than MOSTSOLD_CX boxes
        MOSTSOLD_CX = 5

        lastweek_date = date.today() - timedelta(days=7)
        lastweek = ItemPedido.objects.filter(pedido__data__gte=lastweek_date)

        lastweek_most_dict = defaultdict(int)
        lastweek_lst = []
        
        for lw_pedido in lastweek:
            lastweek_most_dict[lw_pedido.produto.codigo] += lw_pedido.qtde

        for c in lastweek_most_dict:
            if lastweek_most_dict[c] > Produto.objects.get(codigo=c).cx * MOSTSOLD_CX:
                lastweek_lst.append(c)

        lastweek_str = '\n'.join(sorted(lastweek_lst))
        
        form = PreliminaryReportForm({'codigos': lastweek_str})
        warnings = ""
        produtos = Produto.objects.all()
        for p in produtos:
            if p.disp < 0 or p.resv < 0:
                warnings += f"{p.codigo} has negative estoque\n"
            if not p.inativo:
                if p.cx < 1:
                    warnings += f"{p.codigo} has cx 0\n"

        atualizados = {at.tipo: at.data for at in Atualizado.objects.all()}

        containers_chegaram = list(Compra.objects.order_by('-container').values_list('container').distinct())
        containers_chegaram = "\n".join(item[0] for item in containers_chegaram)

        containers_vao_chegar = list(Chegando.objects.order_by('nome').values_list('nome').distinct())
        containers_vao_chegar = "\n".join(item[0] for item in containers_vao_chegar)

        thisYear = date.today().year
        lastYear = thisYear - 1
    
        lastYearBegin = date(lastYear, 1, 1)

        def getPedidoDates(pedidos):
            return sorted(set(datetime.strftime(p.data, "%Y-%m-%d") for p in pedidos), reverse=True)

        def getPedidoDateObjects(pedidos):
            return sorted(set(p.data for p in pedidos), reverse=True)

        datas_com_pedidos = getPedidoDates(Pedido.objects.filter(data__gte=lastYearBegin))
        
        datasStr = "\n".join(datas_com_pedidos)

        # check quality of data
        ptl_pedidos_since_last_year = Pedido.objects.filter(empresa_numero__gte="PON_", data__gte=lastYearBegin)

        uni_pedidos_since_last_year = Pedido.objects.filter(empresa_numero__gte="UNI_", data__gte=lastYearBegin)

        ptl_dates = getPedidoDateObjects(ptl_pedidos_since_last_year)
        uni_dates = getPedidoDateObjects(uni_pedidos_since_last_year)

        for year in range(lastYear, thisYear+1):
            for month in range(1, 13):
                beginningOfMonth = date(year, month, 1)
                endOfMonth = date(year, month, monthrange(year, month)[1])
                if endOfMonth <= date.today():
                    if sum(1 if beginningOfMonth <= d <= endOfMonth else 0 for d in ptl_dates) < 12:
                        warnings += "PTL pedidos for {}/{} is low\n".format(year, month)

                    if year > 2018 and sum(1 if beginningOfMonth <= d <= endOfMonth else 0 for d in uni_dates) < 1:
                        warnings += "UNI pedidos for {}/{} is low\n".format(year, month)

        return render(request, 'relatorios/verificar.html',
                      {'form': form,
                       'warnings': warnings,
                       'atualizados': atualizados,
                       'containers_chegaram': containers_chegaram,
                       'containers_vao_chegar': containers_vao_chegar,
                       'datas_com_pedidos': datasStr,
                      })

   
def preliminaryReport(request, codigoBangs):
    blocks, response_err = getBlocks(codigoBangs)
    thisyr = int(datetime.strftime(date.today(), "%Y"))
    lastyr = thisyr - 1

    return render(request, 'relatorios/preliminaryReport.html', { 'err': response_err, 'blocks': blocks, 'thisyr': thisyr, 'lastyr': lastyr })
    

def xlsReport(request):
    if request.method == "POST":
        selected = request.POST.getlist('selected_cod')
        blocks = getXlsBlocks(selected)
        todayStr = datetime.strftime(date.today(), "%Y-%m-%d")
        
        response = HttpResponse(generateXlsReport(blocks), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename=relatorio-' + todayStr + '.xlsx'
        return response
                                    
    else:
        return redirect('relatorios:verificar')


def uploadcv(request):
    return formDescription(request, "cv", xlcv.create)

relatorios/templates/relatorios/ativos.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(3) Ativos (Opcional)
<br>

Ultima atualizacao {{ data }}<br><br>
Planilha com um codigo ativo por linha
{% endblock %}

relatorios/templates/relatorios/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MultiRepos</title>
<style>
a {
    text-decoration: none;
    font-weight: bold;
}

td {
    padding-right: 7px;
    padding-bottom: 10px;
    vertical-align: top;
}

table.nopad td {
    padding: 0;
}

.monospace {
    font-family: monospace;
    border-collapse: collapse;
}

.nowrap {
    white-space: nowrap;
    padding: 0;
    margin: 0;
}

li {
	margin-bottom: 12px;
}

.dayhl {
    background-color: #9F9;
}

.mocal {
    display: inline-block;
    font-family: monospace;
    margin-right: 15px;
    vertical-align: top;
}

.blue {
    color: blue;
}
</style>
</head>
<body>
<a href="{% url "admin:index" %}" target="_blank">(Admin)</a> &bullet;
<a href="{% url "relatorios:index" %}">(0) Home</a> &bullet;
<a href="{% url "relatorios:produtos" %}">(1) Produtos</a> &bullet;
<a href="{% url "relatorios:caixas" %}">(2) Caixas</a> &bullet;
<a href="{% url "relatorios:ativos" %}">(3) Ativos</a> &bullet;
<a href="{% url "relatorios:estoques" %}">(4) Estoques</a> &bullet;
<a href="{% url "relatorios:containers" %}">(5) Containers</a>
<br><br>
<a href="{% url "relatorios:pedidos" %}">(6) Pedidos</a> &bullet;
<a href="{% url "relatorios:itenspedidos" %}">(7) Itens Pedidos</a> &bullet;
<a href="{% url "relatorios:encomendas" %}">(8) Encomendas</a> &bullet;
<a href="{% url "relatorios:verificar" %}">(9) Codigos para verificar</a>


<!-- 'ativos', 'containers', 'pedidos', 'itenspedidos', 'encomendas', 'vercodigos' -->

<hr>
{% block content %}{% endblock %}
</body>
</html>

relatorios/templates/relatorios/baseform.html
{% extends "relatorios/base.html" %}

{% block content %}

{% block description %}{% endblock %}

<br><br>
{% include 'relatorios/form.html' %}

{% endblock %}

relatorios/templates/relatorios/caixas.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(2) Caixas (Opcional)
<br>
Ultima atualizacao {{ data }}<br><br>

Movimento > Lista de precos > Lista Geral - Ativos
{% endblock %}

relatorios/templates/relatorios/containers.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(5) Containers (Opcional)
<br>

Ultima atualizacao {{ data }}<br><br>
Loja Virtual > Secao PAC > Escolha o container > Clique em Imprimir
{% endblock %}

relatorios/templates/relatorios/cv.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(?) CV
<br>

Ultima atualizacao {{ data }}<br><br>
Planilha Relatorios &gt; Produtos &gt; Precos e Qtdes
{% endblock %}

relatorios/templates/relatorios/estoques.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(4) Estoques
<br>
Ultima atualizacao {{ data }}<br><br>

Relatorios > Produtos > Conferencia de Estoque (Ativo)
{% endblock %}

relatorios/templates/relatorios/form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

relatorios/templates/relatorios/index.html
{% extends "relatorios/base.html" %}

{% block content %}
{% for step in steps %}
<a href="{% url "relatorios:"|add:step %}">{{ step }}</a> |
{% endfor %}

Relatorios Home

<pre>
888b     d888          888 888    d8b 8888888b.                                     
8888b   d8888          888 888    Y8P 888   Y88b                                    
88888b.d88888          888 888        888    888                                    
888Y88888P888 888  888 888 888888 888 888   d88P .d88b.  88888b.   .d88b.  .d8888b  
888 Y888P 888 888  888 888 888    888 8888888P" d8P  Y8b 888 "88b d88""88b 88K      
888  Y8P  888 888  888 888 888    888 888 T88b  88888888 888  888 888  888 "Y8888b. 
888   "   888 Y88b 888 888 Y88b.  888 888  T88b Y8b.     888 d88P Y88..88P      X88 
888       888  "Y88888 888  "Y888 888 888   T88b "Y8888  88888P"   "Y88P"   88888P' 
                                                         888                        
                                                         888                        
                                                         888                        
</pre>



{% endblock %}

relatorios/templates/relatorios/info.html
{% extends "relatorios/base.html" %}

{% block content %}
<pre>
{{ info }}
</pre>
{% endblock %}

relatorios/templates/relatorios/pedidos.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(6) Pedidos (add both)
<br>

Ultima atualizacao {{ data }}<br><br>
Relatorios > Vendas > por Numero > Sintetico
{% endblock %}

relatorios/templates/relatorios/produtos.html
{% extends "relatorios/baseform.html" %}

{% block description %}
(1) Produtos (Opcional)
<br>
Ultima atualizacao {{ data }}<br><br>

Relatorios > Produtos > Precos e Quantidades
{% endblock %}

relatorios/templates/relatorios/result.html
{% extends "relatorios/base.html" %}
{% block content %}
{{ templateVars.tipo }}

{{ response|safe }}
{% endblock %}

relatorios/templates/relatorios/verificar.html
{% extends "relatorios/base.html" %}

{% block content %}
Verificar codigos

<pre style="color: red;">{{ warnings }}</pre>

<div style="display: inline-block; vertical-align: top;">
<table class="nopad">
<tr><td colspan="2">Dados atualizados em:</td></tr>
<tr><td>produtos</td><td>{{ atualizados.produtos|date:"Y-m-d" }}</td></tr>
<tr><td>caixas</td><td>{{ atualizados.caixas|date:"Y-m-d" }}</td></tr>
<tr><td>ativos</td><td>{{ atualizados.ativos|date:"Y-m-d" }}</td></tr>
<tr><td>estoques</td><td>{{ atualizados.estoques|date:"Y-m-d" }}</td></tr>
<tr><td>containers</td><td>{{ atualizados.containers|date:"Y-m-d" }}</td></tr>
<tr><td>pedidos</td><td>{{ atualizados.pedidos|date:"Y-m-d" }}</td></tr>
<tr><td>itenspedidos</td><td>{{ atualizados.itenspedidos|date:"Y-m-d" }}</td></tr>
<tr><td>encomendas</td><td>{{ atualizados.encomendas|date:"Y-m-d" }}</td></tr>
</table>
</div>

<div style="display: inline-block; vertical-align: top;">
Containers que chegaram<br>
<textarea rows="8" cols="15">{{ containers_chegaram }}</textarea>
<br>

Containers que vao chegar<br>
<textarea rows="8" cols="15">{{ containers_vao_chegar }}</textarea>
</div>

<div style="display: inline-block; vertical-align: top;">
Datas com pedidos<br>
<textarea rows="10" cols="20">{{ datas_com_pedidos }}</textarea>
</div>
<br>
<br><hr>

<form method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    
    <input type="submit">
</form>

{% endblock %}